### ISSUE TITLE
GWT compilation fails because of 'nanoTime'

### ISSUE THREAD

**Issue by david-westreicher** [DaanVanYperen/artemis-odb-contrib#101]
I am using artemis odb-contribs with [libgdx](https://github.com/libGDX/libGDX).
In particular just a fork of [artemis-quickstart](https://github.com/DaanVanYperen/libgdx-artemis-quickstart).
In libgdx there is a gradle build task which should compile the game to GWT.
I get the following error:
```
Compiling module net.mostlyoriginal.game.GdxDefinition
   Validating units:
      [ERROR] Errors in 'jar:file:/home/david/.gradle/caches/modules-2/files-2.1/net.mostlyoriginal.artemis-odb/contrib-core/0.11.4/a2908d81178a0643074107aba6287612251e4440/contrib-core-0.11.4-sources.jar!/net/mostlyoriginal/api/system/core/TimeboxedProcessingSystem.java'
         [ERROR] Line 121: The method nanoTime() is undefined for the type System
   [ERROR] Aborting compile due to errors in some input files
```
It seems that `TimeboxedProcessingSystem.java` uses `nanoTime()` which isn't supported in GWT.
Is this expected behaviour or is there a way to still compile it to GWT?

~~I normally don't start every sentence with `i`~~

**Comment by DaanVanYperen** [comment]
This is fixed in the `develop` branch, if you know how to compile and install those in your local maven repo. I'll push out a fix for contrib this weekend!

If under time constraints you could `maven install` develop branch yourself and use it in your project, or strip out contrib.

**Comment by david-westreicher** [comment]
Thx a lot! I'll try the `dev` branch.

**Comment by DaanVanYperen** [comment]
Or i'll forget to publish ;)

**Comment by DaanVanYperen** [comment]
It's ready, just waiting for odb 0.13 to be released during the next few days.

**Comment by DaanVanYperen** [comment]
https://github.com/DaanVanYperen/artemis-odb-contrib/releases/tag/v1.0.0

:D
