### ISSUE TITLE
ExtendedComponentMapperPlugin breaks manual wiring

### ISSUE THREAD

**Issue by Namek** [DaanVanYperen/artemis-odb-contrib#104]
Simply registering `SpriteBatch` to `WorldConfiguration` doesn't wire it to `SpriteBatch` field in systems. Everything works when the plugin is not injected.

**Comment by DaanVanYperen** [comment]
@Namek would you mind providing a code sample or perhaps looking at the regression test below and see what we do differently? I can't seem to reproduce the issue.

```java
@Test
public void Regression_When_superMapper_plugin_in_use_Should_not_break_regular_object_inection() {

		class Injectable {}
		class TestSystem extends BaseSystem {

			private M<TestMarker> mTest;
			@Wire Injectable injectable;

			@Override
			protected void processSystem() {
				Assert.assertNotNull(injectable);
			}
		}

		WorldConfiguration configuration = new WorldConfigurationBuilder()
				.dependsOn(ExtendedComponentMapperPlugin.class)
				.with(new TestSystem())
				.build();

		configuration.register(new Injectable());

		new World(configuration).process();
	}
}
```

**Comment by Namek** [comment]
It's been a long time. So many projects and technologies behind me.

By looking at date and https://github.com/junkdog/artemis-odb/releases it was probably before artemis-odb 1.4.0 so it may be completely outdated problem. I close this since I couldn't find environment (project+setup) where it occured or I have workarounded it.
