### ISSUE TITLE
Gradle could not download the newest jar!

### ISSUE THREAD

**Issue by ks3dev** [DaanVanYperen/artemis-odb-contrib#106]
The PassiveSystem is still the old code.

package net.mostlyoriginal.api.system.core;

import com.artemis.BaseSystem;

/**
 * Headless system.
 *
 * For tickless secondary systems that service primary systems.
 *
 * @author Daan van Yperen
 */
public class PassiveSystem extends BaseSystem {

    public PassiveSystem() {
        setEnabled(false);
    }

    @Override
    protected void processSystem() {
	    // do nothing!
    }
}

------ Gradle Project is not the newest code.
        compile "net.mostlyoriginal.artemis-odb:contrib-core:$artemisContribVersion"
        compile "net.mostlyoriginal.artemis-odb:contrib-jam:$artemisContribVersion"
        compile "net.mostlyoriginal.artemis-odb:contrib-eventbus:$artemisContribVersion"
        compile "net.mostlyoriginal.artemis-odb:contrib-plugin-operations:$artemisContribVersion"

**Comment by DaanVanYperen** [comment]
The latest version depends on unpublished artemis-odb version. When that goes live I'll push contrib live as well!
