### ISSUE TITLE
Would you consider a pull request for a "Box2DPhysicsSystem" ?

### ISSUE THREAD

**Issue by DotProductGaming** [DaanVanYperen/artemis-odb-contrib#131]
Hi, i'm implementing Box2D in my Artemis-odb LibGDX project and I noticed there aren't any sample components (in core or jam) that implement it.  If I create a simple Box2D example system and submit it as a pull request would you consider it?  (if it holds up to your quality I mean)

I was thinking something along the lines of:

`contrib-jam\src\...\api\system\physics\Box2DPhysicsSystem`

which would match on `Pos.class`

Thanks!

**Comment by DaanVanYperen** [comment]
Hey @DotProductGaming. Sorry for the slow response.

The re-usability of such a system would probably be too low for most of the users, as there are so many different ways to fit box2d into ECS. I'm happy to take a look though! Jam isn't exactly re-usability central to begin with.

For your tutorial to reach more people it's probably better to have a repo for it on your profile and make sure people can find it, using the odb wiki, or by adding an box2d open source game to the gallery.
