### ISSUE TITLE
[Systems] Interval system with proper delta

### ISSUE THREAD

**Issue by DaanVanYperen** [DaanVanYperen/artemis-odb-contrib#48]
https://github.com/junkdog/artemis-odb/issues/191

**Comment by DaanVanYperen** [comment]
@Namek would it be possible to instead set `world.delta = GlobalTime.delta;` before process is run? That's how I typically set a custom delta in Artemis.

**Comment by Namek** [comment]
No?

**Comment by DaanVanYperen** [comment]
I mean, can you give some insight of your particular use case that makes that impossible.

**Comment by Namek** [comment]
Sometimes I want to pause the game but not really entirely. That's why I needed to customize flow time per system.

**Comment by DaanVanYperen** [comment]
Makes sense!

**Comment by DaanVanYperen** [comment]
@junkdog already covered in 2014! :D
