### ISSUE TITLE
drop-in basic networking for artemis-odb

### ISSUE THREAD

**Issue by DaanVanYperen** [DaanVanYperen/artemis-odb-contrib#5]
Authoritive server/client setup.

Leverage Artemis' design and make networking accessible out of the box for ecs/networking newbies. High level convention/annotation based networking of components, on top of some networking systems with a nice example or two, client/server system reuse. The actual networking framework can be completely outside ECS.

Take an existing network framework, integrate it in Artemis ECS pattern like you would any externalized framework, and provide enough sauce so it both becomes a drop in solution and a great reference for prototype networking with Artemis.

https://github.com/junkdog/artemis-odb/issues/103

Epic ticket, break up as we go!

*\* Reworked list **
- [ ] udp (lossy) channel
- [ ] tcp (robust) channel
- [ ] client packets
  - [ ] keyboard input packet
  - [ ] network event
    - [ ] refusal handling (client futures, basically a rollback request)
- [ ] mirror entity + component to clients
  - [ ] create from archetype
  - [ ] transfer component state
    - [ ] developer codes component <-> packet
    - [ ] subscribing clients to components 
      - [ ] configurable lossy attributes
      - [ ] configurable lossy update interval.
      - [ ] configurable robust attributes
      - [ ] configurable robust update interval.
  - [ ] removeFromWorld
- [ ] subscribing clients to entities 

**Core**
- [ ] authoritative listener server on client.
- [ ] component delta updates (server to client)
- [ ] scoping (what entities to network) 
- [ ] entity network-id
- [ ] entity level networking metadata (what fields do we sync, how do we sync)
  - [ ] manual entity serialization helper & dirty state detection
  - [ ] automated reflection based (de)serialization helpers & dirty state detection
- [ ] dispatching networked events (see #4)
  - [ ] remote entity instancing 
  - [ ] remote entity destruction
- [ ] customizable lifecycle management.

**Not right now:**
- Component or template level networking metadata.
- support for diverging systems, where client and server have different implementations of the same component.
- dedicated server
- component level networking metadata
- Interpolation
- Extrapolation
- gain/loss, min/max caps on fields.
- UDP support (error correction on lossy protocol)
- GWT support
- Ready system
- Lobby system
- Component recording (rollback for hitscanning)
- Client agnostic networking frameworks / swappable networking frameworks

**Comment by Namek** [comment]
http://bitbucket.org/dermetfan/libgdx-box2d-multiplayer

**Comment by DaanVanYperen** [comment]
Putting in freezer! Spring cleaning.
