### ISSUE TITLE
[Systems] SlicingEntityProcessingSystem

### ISSUE THREAD

**Issue by DaanVanYperen** [DaanVanYperen/artemis-odb-contrib#50]
@junkdog: fixed count or fixed percentage of entities processed each tick,
- [x] timeboxed entities.
- [ ] fixed count / percentage of entities
- [ ] write wiki for both

**Comment by junkdog** [comment]
I'll migrate this once we have the new system/subscription code in place.

**Comment by DaanVanYperen** [comment]
@junkdog can you provide the raw code, I'll get it done!

**Comment by junkdog** [comment]
https://github.com/junkdog/shamans-weirding-game/blob/master/core/src/main/java/com/github/junkdog/shamans/artemis/SlicingEntityProcessingSystem.java

**Comment by DaanVanYperen** [comment]
Added 18ecd6d0331f5c2d5bb825f69b8b55d4cc80280f
