### ISSUE TITLE
BOX2D System

### ISSUE THREAD

**Issue by DaanVanYperen** [DaanVanYperen/artemis-odb-contrib#64]
Delegating things like child/parent to Box2D might be a useful route to take.

**Comment by snorrees** [comment]
What exactly are you looking for here?
A system that runs world.step, manages a physics-component pointing to body? 

When you say parent/child relationship, do you mean hierarchical entity references implicit in joints or something? Mutual assured destruction for an entity-hierarchy?

Collision-listener stuff? Collision-components as flags to handle verified collisions in a CollisionHandlerSystems? Contact lists?

Parameterizing bodies & fixtures? Transient Body-component VS BodyDefinition-component?

**Comment by DaanVanYperen** [comment]
Ideally the odb box2d plugin would provide a drop-in physics solution that is extensible, easy to use and not too restrictive. 

Something that can function both as part of a rapid prototyping kit or as a reference for making your own physics systems.

The basics would cover a bridge between the two environments, and whatever else you would use in most cases (collision detection? builder to help assemble bodies?). The details are not set really, ticket is open for interpretation.

I'd rather have something robust, extensible and easy to use and maintain than cover every single use case out there. 

Remark about parent/child is a reference to #26.

**Comment by snorrees** [comment]
I'll get back to you when I start breaking up my shitty game-code. I think there are at least some things in there worth keeping. 

I dont really see how Box2d would help you with parent/child entity-hierarchies though...

**Comment by DaanVanYperen** [comment]
It's an exploratory topic for me, so if there's a better way that'd be great! ;)

**Comment by DaanVanYperen** [comment]
Spring cleaning.
