### ISSUE TITLE
odb smoothcam?

### ISSUE THREAD

**Issue by DaanVanYperen** [DaanVanYperen/artemis-odb-contrib#66]
https://github.com/semperhilaris/smoothcam

**Comment by junkdog** [comment]
pertinent: https://docs.google.com/document/d/1iNSQIyNpVGHeak6isbP6AHdHD50gs8MNXF1GCf08efg/pub?embedded=true

**Comment by DaanVanYperen** [comment]
Out of scope, needs a sponsor.
