### ISSUE TITLE
Non invasive loading debug plugin with (ao) Namek's profiler.

### ISSUE THREAD

**Issue by DaanVanYperen** [DaanVanYperen/artemis-odb-contrib#70]
- [ ] Check out state of @Namek's debug stuff.
- [ ] Factorio like extendable debugging for systems.

**Comment by DaanVanYperen** [comment]
Spring cleaning.

**Comment by Namek** [comment]
I'm currently rewriting my debugger's UI. It internally supports full Java serialisation so it's now possible to represent objects and arrays of objects besides primitives. I'm very close to have same functionality as in old version, next I plan to make it more useful \o/

> Factorio like extendable debugging for systems.

I haven't played Factorio, would you show me or describe what you meant there?
