### ISSUE TITLE
Broken javadoc

### ISSUE THREAD

**Issue by snorrees** [DaanVanYperen/artemis-odb-contrib#71]
`mvn clean install` does fails build due to errors in the javadoc.

Quickest fix is to just remove the maven-javadoc-plugin and maven-source-plugin from the main-pom, since there is also a release profile which does this.

**Comment by DaanVanYperen** [comment]
I'm aware dev is broken, or are you testing master?

**Comment by antag99** [comment]
See [this question](http://stackoverflow.com/questions/22528767/jdk8-and-javadoc-has-become-very-strict) on StackOverflow. I usually just suppress the errors.

**Comment by snorrees** [comment]
Ah sorry, just did a regular old clone + build - so probably dev. Was just helping @piotr-j setting up a benchmark, and he was havning trouble getting it built.

**Comment by DaanVanYperen** [comment]
Fixed in dev! Thanks for report.
