### ISSUE TITLE
Quick and cheap toggle-profiler plugin

### ISSUE THREAD

**Issue by DaanVanYperen** [DaanVanYperen/artemis-odb-contrib#72]
System invocation strategy + fast rendering solution.

**Comment by piotr-j** [comment]
WIP implementation for reference, features Invocation Strategy, Scene2d and ShapeRenderer based graph and gui. PR to come once enough dog fooding finishes.
https://github.com/piotr-j/libgdxplayground/tree/master/core/src/io/piotrjastrzebski/playground/ecs/profiler
Relevant classes:
ECSShapeProfilerTest
ProfilerSystem.
SystemProfiler
SystemProfilerGUI
