### ISSUE TITLE
Automatically managed references

### ISSUE THREAD

**Issue by DaanVanYperen** [DaanVanYperen/artemis-odb-contrib#77]
Code generation, clear expired ID's on components using generated code.  Replaces EntityReferences.

- [ ] `@EntityId int`
- [ ] Entity
- [ ] `@EntityId IntBag`
- [ ] Bag<Entity>
- [ ] GWT Support

**Comment by DaanVanYperen** [comment]
@junkdog what do you think, might be nice and transparent, or is this over engineering it? 
Pretty sure we if we can weave it the GWT is relatively peanuts.

Thinking of generating something like
```java
MyComponent extends PooledComponent implements Listener {

   public @EntityId int entityA;
   public @EntityId IntBag entitiesB;
   public Entity entityC;
   public Bag<Entity> entitiesD;

   public _remove(int id) {
           if ( entityA == id ) entityA = null;     
           ..
   }
}
```

Hmmm guess performance won't be the best.

**Comment by DaanVanYperen** [comment]
Considered alternatives
- `EntityReference` requires some setup and unwrapping by the user and is impossible to pool, plus clashes a bit with io.
- Considered a EntityVersionManager and a corresponding long that holds entityId+version.

**Comment by DaanVanYperen** [comment]
Edit: Without a way to subscribe it would have to cycle all components vs all deleted entities O(n2). We could add a dirty check that builds a lookup index before the delete cycle? That could make it O(n) components O(n) entities.

**Comment by junkdog** [comment]
> Manually managing references is a pain in the butt.

Hmm, I need to look closer into this, because I've never had a problem with specifically tracking references. Probably because I've never faced the use-case where it's tricky to track.

Early NPE for deleted entities could be solved via the pre-processed debug build, but I guess that won't suffice?

What about something like:

```java
@AutoManagedEntityReferences // verbosity aside...
class MyComponent extends PooledComponent {

   public @EntityId int entityA;
   public @EntityId IntBag entitiesB;
   public Entity entityC;
   public Bag<Entity> entitiesD;
}
```

Reflection-based removal for normal behavior, auto-managed when weaving. The perf hit is potentially pretty big though. `entitiesB` and `entitiesD` should be backed by a bitset for quick lookup, at least.

**Comment by junkdog** [comment]
`@AutoManagedEntityReferences` would prob tie into a ReferenceEntityManager or such.

**Comment by DaanVanYperen** [comment]
> Hmm, I need to look closer into this, because I've never had a problem with specifically tracking references. Probably because I've never faced the use-case where it's tricky to track.

We're both very acquainted with the system so that's what I'd expect. ;)

One argument is Artemis is effectively a life-cycle management framework. It black boxes everything about life-cycle management, except for entity references? Ints getting recycled is part of the black box but somehow ends up on the devs plate. So new devs get unexpected fail-slow issues that are hard to trace back to origin 

Besides that there's the argument of convenience, cleanup of referencing entities is something you'd ideally do once, centralized and transparently.

> Reflection-based removal for normal behavior, auto-managed when weaving

I didn't even consider reflection as feasible. You feel weaving is a bad requirement for dev's if can cover all the platforms? Guess it'd break typical IDE use.

> entitiesB and entitiesD should be backed by a bitset for quick lookup, at least.

After sleeping about it a night I feel this is over engineered. Id validation is something odb should intrinsically solve.
