### ISSUE TITLE
Fire and forget systems

### ISSUE THREAD

**Issue by DaanVanYperen** [DaanVanYperen/artemis-odb-contrib#84]
For those once-off systems to setup a world, but you don't want in your cycle.

**Comment by DaanVanYperen** [comment]
Out of scope, requires a sponsor.

**Comment by schosin** [comment]
This would be a good fit for initializing singleton components, e.g. loading a (read-only) configuration or assets.
But I don't see how that would be possible without a custom SystemInvocationStrategy. And those are not very composable (I already have a strategy, which handles two unrelated features, which I don't really like. This would be the third).

I feel like this is more of a artemis-odb feature.

**Comment by DaanVanYperen** [comment]
You are right. Essentially hooking into the initialisation phase, but not the processing phase of odb. 

Been considering
- Making the initialisation phase extendable.
- Native support for the [odb best practices](https://github.com/junkdog/artemis-odb/wiki/Best-Practices), specifically the dependencies bit (see below). (from the [Overwatch ECS talk](https://youtu.be/W3aieHjyNvw)).
- Simplified system hierarchy with composed/extendable behaviour via other means.

But in the end it's quite a big pivot for odb which might not be in the best interest of current users.

![image](https://user-images.githubusercontent.com/6305602/67158599-764e3380-f33a-11e9-8672-34a85b5ee36b.png)
