### ISSUE TITLE
Update Wiki

### ISSUE THREAD

**Issue by DaanVanYperen** [DaanVanYperen/artemis-odb-contrib#90]
- [ ] Quadtree
- [ ] Operations 
- [ ] Performance

**Comment by alwex** [comment]
Hi do yu have a realease date for this 1.0.0 version?
Nice contrib by the way

**Comment by fabioticconi** [comment]
..and Network stuff, unless that's currently broken/unfinished?

**Comment by DaanVanYperen** [comment]
Spring cleaning.
