### ISSUE TITLE
Revisit Scheduler for pooling.

### ISSUE THREAD

**Issue by DaanVanYperen** [DaanVanYperen/artemis-odb-contrib#95]
- [ ] manage lifecycle component states for tween.
- [ ] Allow merging schedules.
- [ ] better definition of parallel actions.
- [ ] write test for components (Delay, add, remove)

**Comment by antag99** [comment]
I've finished an implementation of "commands" in my jam library - it looks like this:
```java

public abstract class Command implements Poolable {

    public abstract float apply(Entity entity, float time);

    public abstract void restart();

    @Override
    public void reset() {
        restart();
    }
}
```

Commands are wired up using the `Commands` class, which allocates them from `Pools`. Commands that execute other commands *own* them - so `RepeatCommand` frees it's command when `reset()` is called.

I hope to push this to the retinazer repo pretty soon, but there are lots of unit tests to write and stuff to polish.

**Comment by DaanVanYperen** [comment]
@antag99 I took a look at libgdx actions and it just reinforces the feeling we're all making the same things over and  over again ;)
